typography_spectrum: 0.7671880025882274
color:
  brandStrength: 0.3744568289257586
  lightness: 0.5568871607538313
  saturation: 0.7353385351598263
  rhythmicContrast: 0.2667609218042344
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.341251123463735
name: responsible freedom
navigation:
  - name: '         Barbra Keeps it Coming'
    id: dea40909-b7ff-4852-9fba-f3f3529c6fbb
    type: content
  - name: 'Rising dawn: Rolls-Royce'
    id: 929cde32-0ab1-4d0d-84b1-a73f6484d878
    type: content
  - name: Platterless Turntable
    id: de498d55-1d1a-45f1-ba6e-dc45d889c068
    type: content
title: for what it's worth
description: really useful stuff
